//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkDevices
    {
        public int ID { get; set; }
        public int ID_Type { get; set; }
        public int ID_Producer { get; set; }
        public string Model { get; set; }
        public int Number_of_ports { get; set; }
    
        public virtual Producer Producer { get; set; }
        public virtual Type Type { get; set; }
    }
}
